import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";

import { GeistSans } from "geist/font/sans";
import TopNav from "./_components/topnav";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "sonner";
import { CSPostHogProvider } from "./_analytics/provider";

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber to Theo on YouTube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <CSPostHogProvider>
        <html lang="en" className={`${GeistSans.variable} dark`}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body className="">
            <div className="w-full">
              <div className="h-screen grid grid-rows-[auto,1fr]">
                <TopNav />
                <main className="overflow-y-scroll">{children}</main>
              </div>
              {modal}
              <Toaster />
              <div id="modal-root"></div>
            </div>
          </body>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
